// Generated by tools/gen_pinyin_data.py - do not edit.
// One row per searchable effect/preset, with precomputed pinyin keys.
//
// The table itself lives in pinyin_data.cpp: this header used to define it,
// which put a private copy in every translation unit that included it
// (the 2212-row table is ~190 KB of .rdata per copy).
#pragma once

struct PinyinEntry {
    const char* full;      // full pinyin, e.g. gaosimohu
    const char* initials;  // first letters, e.g. gsmh
    const char* name;      // display name (chinese on a chinese AE)
    const char* english;   // english name
    int is_preset;         // 1 = preset, 0 = effect
    const char* path;      // presets only: path under the Presets folder
    const char* vendor;    // class behind the @ filter, empty for built-ins
};

extern const PinyinEntry kPinyinEntries[];
extern const int kPinyinEntryCount;

// Short keys for the "@" filter ("@BFX" == "@Boris FX").
struct PinyinVendorAlias {
    const char* key;
    const char* vendor;
};
extern const PinyinVendorAlias kPinyinVendorAliases[];
extern const int kPinyinVendorAliasCount;
