# -*- coding: utf-8 -*-
"""Generate the C++ search index from build/ae-index.json.

Writes two files into the SDK project:
  pinyin_data.h    declarations (struct + extern tables)
  pinyin_data.cpp  the 2212-row table and the vendor alias table

Two things are generated rather than hand-written, so a newly installed plug-in
only needs this script to be re-run:
  * the rows themselves (names, pinyin keys, vendor, preset path)
  * the short aliases used by "@BFX" style queries - one per effect vendor,
    with the manual overrides below pinning the ones worth remembering.
"""
from __future__ import annotations

import json
import re
from collections import Counter
from pathlib import Path

SRC = Path(r"H:\ae-pinyin-search\build\ae-index.json")
OUT_H = Path(r"H:\ae-sdk\AfterEffectsSDK_26.5_win\Examples\AEGP\AEPinyinSearch\pinyin_data.h")
OUT_CPP = Path(r"H:\ae-sdk\AfterEffectsSDK_26.5_win\Examples\AEGP\AEPinyinSearch\pinyin_data.cpp")

# Short keys that must exist no matter what the auto rule would invent. A key
# whose name is a PREFIX of real classes covers the whole family, so "text"
# reaches every "Text\..." preset category.
MANUAL_ALIASES = {
    "bfx": "Boris FX",
    "rgu": "Red Giant Universe",
    "rgv": "Red Giant VFX",
    "sap": "Sapphire",
    "trap": "Trapcode",
    "mb": "Magic Bullet",
    "vc": "Video Copilot",
    "legacy": "Legacy",
    "text": "Text",
    "shapes": "Shapes",
    "trans": "Transitions",
    "image": "Image",
    "bg": "Backgrounds",
    "beh": "Behaviors",
    "syn": "Synthetics",
    "sfx": "Sound Effects",
    "ae": "Adobe Express",
}


def vendor_alias(vendor: str) -> str:
    """Initials of the words: "Red Giant Universe" -> "rgu"."""
    words = [w for w in re.split(r"[^0-9A-Za-z]+", vendor) if w]
    if len(words) >= 2:
        return "".join(w[0].lower() for w in words)
    return re.sub(r"[^0-9a-z]+", "", vendor.lower())


def alias_covers(name: str, vendor: str) -> bool:
    """Does the manual entry `name` stand for this vendor (maybe a whole family)?"""
    if vendor == name:
        return True
    if not vendor.startswith(name):
        return False
    return len(vendor) > len(name) and vendor[len(name)] in " \\/-_"




def cstr(s: str) -> str:
    """Escape a python string for a C string literal (UTF-8 source)."""
    out = []
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        elif ord(ch) < 0x20:
            out.append("\\x%02x" % ord(ch))
        else:
            out.append(ch)
    return "".join(out)


def main() -> int:
    data = json.loads(SRC.read_text(encoding="utf-8"))
    rows = []
    for e in data.get("effects", []):
        # vendor is the "class" behind the @ filter: Boris FX / Sapphire /
        # Red Giant Universe ... (empty for the built-ins).
        rows.append((e.get("f", ""), e.get("i", ""), e.get("n", ""), e.get("e", ""), 0, "",
                     e.get("vendor", "")))
    for e in data.get("presets", []):
        # Presets need their file path: they are applied with applyPreset(), not
        # addProperty(), so the row has to carry the .ffx location. Their class is
        # the preset category folder.
        rows.append((e.get("f", ""), e.get("i", ""), e.get("n", ""), e.get("e", ""), 1,
                     e.get("path", ""), e.get("cat", "")))

    lines = [
        "// Generated by tools/gen_pinyin_data.py - do not edit.",
        "// One row per searchable effect/preset, with precomputed pinyin keys.",
        "//",
        "// The table itself lives in pinyin_data.cpp: this header used to define it,",
        "// which put a private copy in every translation unit that included it",
        "// (the 2212-row table is ~190 KB of .rdata per copy).",
        "#pragma once",
        "",
        "struct PinyinEntry {",
        "    const char* full;      // full pinyin, e.g. gaosimohu",
        "    const char* initials;  // first letters, e.g. gsmh",
        "    const char* name;      // display name (chinese on a chinese AE)",
        "    const char* english;   // english name",
        "    int is_preset;         // 1 = preset, 0 = effect",
        "    const char* path;      // presets only: path under the Presets folder",
        "    const char* vendor;    // class behind the @ filter, empty for built-ins",
        "};",
        "",
        "extern const PinyinEntry kPinyinEntries[];",
        "extern const int kPinyinEntryCount;",
        "",
        "// Short keys for the \"@\" filter (\"@BFX\" == \"@Boris FX\").",
        "struct PinyinVendorAlias {",
        "    const char* key;",
        "    const char* vendor;",
        "};",
        "extern const PinyinVendorAlias kPinyinVendorAliases[];",
        "extern const int kPinyinVendorAliasCount;",
        "",
    ]

    cpp = [
        "// Generated by tools/gen_pinyin_data.py - do not edit.",
        '#include "pinyin_data.h"',
        "",
        "extern const PinyinEntry kPinyinEntries[] = {",
    ]
    for full, ini, name, eng, preset, path, vendor in rows:
        cpp.append(
            '    {"%s", "%s", "%s", "%s", %d, "%s", "%s"},'
            % (cstr(full), cstr(ini), cstr(name), cstr(eng), preset, cstr(path), cstr(vendor))
        )
    cpp.append("};")
    cpp.append("")
    cpp.append("extern const int kPinyinEntryCount = %d;" % len(rows))
    cpp.append("")

    # --- vendor aliases -----------------------------------------------------
    # Manual entries first (they may cover a whole family), then an auto key for
    # every vendor no manual entry speaks for. A vendor that appears later, from
    # a newly installed plug-in, therefore gets a key on its own.
    vendors = {}
    for row in data.get("effects", []):
        v = (row.get("vendor") or "").strip()
        if v:
            vendors[v] = vendors.get(v, 0) + 1
    for row in data.get("presets", []):
        v = (row.get("cat") or "").strip()
        if v:
            vendors[v] = vendors.get(v, 0) + 1

    alias_rows = []
    for key, name in MANUAL_ALIASES.items():
        alias_rows.append((key, name))

    aliases_by_name = {name: key for key, name in MANUAL_ALIASES.items()}
    taken = set(aliases_by_name)
    for vendor in sorted(vendors):
        if any(alias_covers(name, vendor) for name in aliases_by_name):
            continue
        key = vendor_alias(vendor)
        if key in taken:
            print(f"  !! alias collision for {vendor!r} on {key!r}, using the full name")
            key = re.sub(r"[^0-9a-z]+", "", vendor.lower())
        taken.add(key)
        aliases_by_name[vendor] = key
        alias_rows.append((key, vendor))

    cpp.append("extern const PinyinVendorAlias kPinyinVendorAliases[] = {")
    for key, name in alias_rows:
        cpp.append('    {"%s", "%s"},' % (cstr(key), cstr(name)))
    cpp.append("};")
    cpp.append("")
    cpp.append("extern const int kPinyinVendorAliasCount = %d;" % len(alias_rows))
    cpp.append("")

    print("classes and their keys:")
    for vendor, n in sorted(vendors.items(), key=lambda kv: -kv[1]):
        key = next((k for name, k in aliases_by_name.items() if alias_covers(name, vendor)), "(none)")
        print(f"  @{key:<12} {vendor:<26} {n:5}")
    print("alias rows:", len(alias_rows))

    OUT_H.write_text("\n".join(lines), encoding="utf-8")
    OUT_CPP.write_text("\n".join(cpp), encoding="utf-8")
    print("entries:", len(rows))
    print("wrote:", OUT_H, OUT_H.stat().st_size, "bytes")
    print("wrote:", OUT_CPP, OUT_CPP.stat().st_size, "bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
